name: Manage Infrastructure

on:
  push:
    branches:
      - main
      - destroy-branch

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Terraform Init & Plan
        run: |
          terraform init -input=false
          terraform plan -out

      - name: Persist Terraform files
        uses: actions/upload-artifact@v2
        with:
          name: terraform-files
          path: ./

  apply:
    runs-on: ubuntu-latest
    needs: plan-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Attach Terraform files
        uses: actions/download-artifact@v2
        with:
          name: terraform-files
          path: ./

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve

